language: go

install:
  - GO111MODULE=on go get github.com/itsubaki/appstore

script:
  - GO111MODULE=on go test -v ./...

after_script:
  - appstore ranking -c us
  - appstore review pokemon -c us -s
